# Generated by Django 3.2 on 2025-06-04 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='image',
            new_name='imagen',
        ),
    ]
